synced
ACMILabs/interactive-label pull request #59
Opened 2020-10-28 03:31 UTC by hvanness

Resolves ACMILabs/xos#2429

2020-11-18 07:20 UTC, sighmon commented
Would prefer you to put in a new pull request for the new designs. This one didn't resolve the issues it was trying to anyway.

2020-11-23 02:54 UTC, hvanness commented
Reopening this PR since it is necessary to resolve inconsistencies before continuing development.

2020-11-23 22:38 UTC, sighmon commented
@hvanness Can you still start Interactive Labels locally? I'm seeing: `Error downloading playlist JSON from XOS: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

```bash
$ docker-compose up
Recreating labelinteractive ... done
Attaching to labelinteractive
labelinteractive    | Error downloading playlist JSON from XOS: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
labelinteractive    |  * Serving Flask app "main" (lazy loading)
labelinteractive    |  * Environment: development
labelinteractive    |  * Debug mode: off
labelinteractive    |  * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
```

2020-11-23 22:55 UTC, sighmon requested changes
I'm still seeing differences between the XOS preview and the Interactive Label.

Interactive Label:
* Font family is wrong for the child titles
* Font size is too big for the child titles
* Filename shows below the image

![Screen Shot 2020-11-24 at 9 20 40 am](https://user-images.githubusercontent.com/314298/100024315-6e629c00-2e36-11eb-80d0-67a8c22038ad.png)
![Screen Shot 2020-11-24 at 9 23 10 am](https://user-images.githubusercontent.com/314298/100024450-b7b2eb80-2e36-11eb-869d-18b6667c5b3e.png)

2020-11-24 03:35 UTC, hvanness commented
You probably need to check out the updated XOS branch.
Looks like you were able to resolve the 'Connection aborted' issue.

2020-11-24 07:46 UTC, sighmon approved these changes
Oh right sorry, didn't click that the column html was being generated by XOS. Thought there was still some css bug.

2020-11-24 23:33 UTC, merged